### ISSUE TITLE
LegoSystem_BoostHub

### ISSUE THREAD

**Issue by LukeOwlclaw** [sharpbrick/powered-up#133] opened 2020-12-27 06:09 UTC
I got hands on a Lego Boost and just noticed that 

    SystemType.LegoSystem_BoostHub

is defined but there is not `BoostHub` implementation. Is there anything going on on that front where I could chime in?

**Comment by tthiery** [comment] 2020-12-27 08:57
There is nothing going on because I miss the hardware. Further, when I read/remember the node-poweredup library the boost hub is very different (using multiple bluetooth characteristics etc). It will significantly break all layers.

I am very open to contribution but it will be neither a small job nor easy 😁. I will help with all needed advice and assistance.

**Comment by tthiery** [comment] 2020-12-27 12:43
Maybe I am wrong. Maybe I am confused with the WeDo 2.0 sets. I think the Boost hubs are called MoveHub. There is issue #95 Add Move Hub which seems pretty compliant which makes the whole adoptation a lot simpler. If you like you can throw yourself on that issue.

**Comment by tthiery** [comment] 2020-12-30 13:18
Duplicate of #95. Will be added in #134

**Closed by tthiery** 2020-12-30 13:18 UTC
Labels: duplicate
